name: if condition
on:
  push:
    branches:
      - main
jobs:
  conditional_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set x
        run: echo "x=12" >> $GITHUB_ENV

      - name: Conditional Step
        if: ${{ env.x > '2' }}
        run: echo "x is greater than 2"
      
      - name: Next Step
        if: ${{ env.x <= '2' }}
        run: echo "x is not greater than 2 ${{ env.x }}"
